/*
 * 이보슬 문제02
 * 
 * EMPLOYEES테이블에서 FIRST_NAME의 글자수가 5개이고 고용년도가 1998~2000 사이인 직원들의 
 * EMPLOYEE_ID, FIRST_NAME, EMAIL, HIRE_DATE를 조회하시오.
 * 	- EMAIL은 'EMAIL@gmail.com'와 같은 형식으로 출력되도록 하고 EMAIL 이라고 별칭을 부여한다.
 * 	- HIRE_DATE는 년도만 출력되도록 하고 HIRE_YEAR 라고 별칭을 부여한다. 
 */


SELECT EMPLOYEE_ID 
	 , FIRST_NAME
	 , CONCAT(EMAIL, '@gmail.com') EMAIL 
	 , EXTRACT(YEAR FROM HIRE_DATE) HIRE_DATE 
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '_____'
  AND EXTRACT(YEAR FROM HIRE_DATE) BETWEEN 1998 AND 2000;
  
 
SELECT EMPLOYEE_ID 
	 , FIRST_NAME
	 , CONCAT(EMAIL, '@gmail.com') EMAIL 
	 , EXTRACT(YEAR FROM HIRE_DATE) HIRE_DATE 
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '_____'
  AND EXTRACT(YEAR FROM HIRE_DATE) IN(1998,1999,2000);

 